// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqbhdmbzbkxwjgslvkjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxYmhkbWJ6Ymt4d2pnc2x2a2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzAyNDgsImV4cCI6MjA3MjUwNjI0OH0.fNyHIQT_zZKfmLzZBeWQnEJBnWUA8dmbu7kreAFy8-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});